# This file was generated by GoReleaser. DO NOT EDIT.
cask "hb-test" do
  name "hb-test"
  desc ""
  homepage ""
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hb-test"

  on_macos do
    on_intel do
      url "https://github.com/mvgrimes/hb-test/releases/download/#{version}/hb-test_Darwin_x86_64.tar.gz"
      sha256 "d12dc8ec7efb652528bbd82002be63001e57d983bf95d5ca97c88102106ef454"
    end
    on_arm do
      url "https://github.com/mvgrimes/hb-test/releases/download/#{version}/hb-test_Darwin_arm64.tar.gz"
      sha256 "a8138fed8d7549e39e6bcab1d59048b07792694a5f936803c8f39d0fb451249b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvgrimes/hb-test/releases/download/#{version}/hb-test_Linux_x86_64.tar.gz"
      sha256 "a4a8a6ec38006be8c03522297c9c1f8cb59485bf15ce48f690af44ba5005c89a"
    end
    on_arm do
      url "https://github.com/mvgrimes/hb-test/releases/download/#{version}/hb-test_Linux_arm64.tar.gz"
      sha256 "3cb005113b9fe8dea28fc26ea89dc30385a69ef5fb6591edafa1fcb94900251c"
    end
  end

  # No zap stanza required
end
